### ISSUE TITLE
Not using Hydrus-flavored assembly WF

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/hydrus#312]
Hydrus has it's own flavor of the assembly workflow: https://github.com/sul-dlss/hydrus/blob/master/config/assemblyWF_hydrus.xml

Note: This should not be confused with the hydrusAssemblyWF, which is different.

The key distinctions between this workflow and the normal assembly workflow is that the content-metadata-create step is omitted, the jp2-create step is marked as skipped, and the start-assembly is marked with the "pipelined" lifecycle. Note that both are named "assemblyWF".

**In recent changes to the workflow service, workflows are created by name, not by passed XML.** Thus, when Hydrus creates an assembly workflow, a normal assembly workflow is created, not a Hydrus-flavored assembly workflow.

The question then is: Can Hydrus use the normal assembly workflow and the Hydrus flavored be removed? Or should the Hydrus flavored assembly workflow be elevated to a "first class" workflow?

Corollary question: If the Hydrus flavored assembly workflow should be elevated, what should it be named since hydrusAssemblyWF is already taken?

**Comment by justinlittman** [comment]
On the differences between the Hydrus flavored assembly workflow and the normal assembly workflow:
1. lifecycle=pipelined: This is used at https://github.com/sul-dlss/hydrus/blob/e49f6f79daaf2d8cd97ab884ee068894ca1396fd/app/models/hydrus/processable.rb#L103 to determine if an item is accessioned. However, I believe this is a legacy of the old workflow system and simply checking the accessioned lifecycle should be adequate.
2. content-metadata-create: The content metadata robot will return if content metadata already exists. https://github.com/sul-dlss/common-accessioning/blob/master/robots/dor_repo/assembly/content_metadata_create.rb#L22
3. jp2-create: Does it matter if jp2s are created? We don't we want them created? Perhaps we can mark that step as skipped after the worflow is created?

**Comment by blalbrit** [comment]
Missed the second comment above - and wanting to loop in @hannahfrost - this is my take:

1. Yes, I think pipelined is legacy and could be dropped - unless the app relies upon it for some reporting/status that faces the users (in which case, we should figure out how to use the normal status reporting in workflows to do the same thing)
2. I think Hydrus app creates a content-metadata stub (like goobi). That stub will be the basis for content-metadata once the object hits common-assembly/accessioning. It is likely there that content type is being set to file and resource type also set to file, before passing to assembly. Eventually, Hydrus would like to have the ability to offer different content types - but for now, if we can force ContentType and ResourceType=file, then contentMD creation could happen either in-app or in assembly
3. It doesn't matter if jp2s get created, contentType "file" should just throw them away. it would be wasted effort but, in our current operations, images only rarely get submitted through self-deposit anyway so it might be a non-problem. Assembly may already set jp2-create to skipped for content or resource type = file?

There is a larger question about Hydrus that we should consider in making these changes. The app caches the binaries and metadata files for every object in the /data mount so that users have instant access to their binaries. This causes some problems, occasionally, for updating and managing objects (syncing between DOR/SDR and the cache available to the app can fail or get bypassed if major work is done on the dor side). I think - and Hannah should confirm - that ideally we want to retain immediate access to the most recent binaries for an object within the app but it's possible that the strategy for storing Fedora datastreams as XML files in the /data cache should be rethought.

**Comment by hannahfrost** [comment]
Thanks for looping me in, @blalbrit . I can confirm that the app should retain the binaries for immediate access. It's useful to be able to access them there, in that context, whether they have been submitted to SDR or not. I'm not opinionated about storing the Fedora datastreams as XML in the app.
