### ISSUE TITLE
Author field is no longer validated for containing a value

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/hydrus#42]
It is a functional requirement that at least one author value is entered in the Hydrus item form before the depositor can publish the item. 

Sometime in the recent past, this functionality broke and it is possible to deposit an item with an empty author field.

**Comment by peetucket** [comment]
An older previously created item does not exhibit this behavior (https://hydrus-prod.stanford.edu/items/druid:gr221wr5835) but a newly created item does (https://hydrus-prod.stanford.edu/items/druid:cc544ys2156)

**Comment by peetucket** [comment]
Correction: behavior is the same in both cases...but the empty field that shows by default counts as an author even if no value is entered in the text box for the name.  Since by default we show a row when the page is rendered for a new item, if you just click save, you will get an author with a blank name, which is being counted as an entry.  If you explicitly delete that row with the trash can icon and save, it will validate correctly.
![screen shot 2017-04-04 at 3 38 32 pm](https://cloud.githubusercontent.com/assets/47137/24682125/f03898e0-194c-11e7-802d-d8d0fc916dc6.png)

**Comment by peetucket** [comment]
A quick attempt at a fix here (needs a test still): https://github.com/sul-dlss/hydrus/pull/44
